### ISSUE TITLE
Strange behavior in Safari v9

### ISSUE THREAD

**Issue by Hypercubed** [d3/d3-dispatch#11]
I'm hesitant to report this here because the issue is so intermittent that I'm positive it's a safari bug.

If you run the following gist (gist: https://gist.github.com/Hypercubed/c4276ed96ff4bd575933c7ad390a7a92, block: http://bl.ocks.org/Hypercubed/c4276ed96ff4bd575933c7ad390a7a92) in chrome or firefox you see the expected result.  "called 3000 times total" is written to the DOM.

But run in Safari v9, (and this is crucial) with the debugging console closed, I see `undefined value at XXXX`.  The value that the undefined value starts and ends varies between refreshes.

Seems like a browser bug, but I only see this behavior in d3-dispatch: https://github.com/Hypercubed/EventsSpeedTests/blob/master/results/safari-v9.md

**Comment by mbostock** [comment]
Fixed in 0.4.4; see 893b6f403c2e057208aea1bb30ba5623e2c38ccd. Thanks for the report.

**Comment by Hypercubed** [comment]
Wow, quick fix!!!  I was pulling my hair out (what little I have left).
