### ISSUE TITLE
API Proposal

### ISSUE THREAD

**Issue by curran** [d3/d3-dispatch#16]
When using this library, I have found it cumbersome to always specify the second argument of `dispatch.call`, which I have never had a use for so ends up being `null`, like this:

`dispatch.call("start", null, "I am an argument")`

Proposal for additional API, which would not support any `this` arg:

`dispatch("start", "I am an argument")`

Any thoughts?

**Comment by mbostock** [comment]
That would require this class to be implemented as a decorated function, similar to scales, and in general I’d like to avoid that pattern as it is more efficient to use classes. Also, I think there’s some benefit to force callers to be explicit about the this context when they dispatch. Thanks for the comment!
