### ISSUE TITLE
Support for multiple callbacks

### ISSUE THREAD

**Issue by devth** [d3/d3-dispatch#22]
> If a callback was already registered for the given typenames, the existing callback is removed before the new callback is added.

Have you considered allowing multiple callbacks for a given typename?

**Comment by mbostock** [comment]
You can use names to register multiple callbacks for the same event type:

```js
dispatch.on("start", callback1);
dispatch.on("start.foo", callback2);
```

**Comment by devth** [comment]
Ah, I missed that. Thanks!
