### ISSUE TITLE
Either fail gracefully or emit useful error message .on("unknownEvent")

### ISSUE THREAD

**Issue by syntagmatic** [d3/d3-dispatch#9]
Using `.on` to listen to an event that doesn't exist triggers an error on https://github.com/d3/d3-dispatch/blob/b2944af8d0db88b813bac7e1926e855019078ab2/src/dispatch.js#L19

Possible solutions:
- `parseTypenames` filters out undefined event types
- error alerts the full event name that couldn't be matched to an event

**Comment by mbostock** [comment]
I’m somewhat averse to error messages because the error should be pretty obvious from the stack trace, and debuggers are far more effective at debugging than reading error messages. But, okay.
